# Generated by Django 3.1.4 on 2021-01-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0003_auto_20201228_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='name',
            new_name='username',
        ),
    ]
