# Generated by Django 3.1.4 on 2021-01-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0004_auto_20210105_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='phone',
        ),
    ]
