# Generated by Django 3.1.4 on 2021-01-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0005_remove_signup_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
