# Generated by Django 3.1.4 on 2021-01-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0007_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TODO',
        ),
    ]
